# Generated by Django 5.2 on 2025-04-27 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('visited', 'Visited'), ('want_to_visit', 'Want to Visit'), ('not_visited', 'Not Visited')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_statuses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
